# Go parameters
GOCMD=go
GOINSTALL=$(GOCMD) install
GOCLEAN=$(GOCMD) clean
GOTEST=$(GOCMD) test
GOGET=$(GOCMD) get
GOGENERATE=$(GOCMD) generate
    
all: test install

test: test_protocol

install: spi i2c mihome sensordb ener314

i2c:
	$(GOINSTALL) -tags "rpi i2c" ./cmd/bme280/...
	$(GOINSTALL) -tags "rpi i2c" ./cmd/bme680/...
	$(GOINSTALL) -tags "rpi i2c" ./cmd/tsl2561/...
	$(GOINSTALL) -tags "rpi i2c" ./cmd/ads1015/...

spi:
	$(GOINSTALL) -tags "rpi spi" ./cmd/bme280/...
	$(GOINSTALL) -tags "rpi spi" ./cmd/bme680/...

generate:
	$(GOGENERATE)  ./rpc/protobuf/...

ener314:
	$(GOINSTALL) -tags "rpi" ./cmd/ener314/...

mihome: 
	$(GOINSTALL) -tags "rpi spi" ./cmd/mihome/...
	$(GOINSTALL) -tags "rpi spi" ./cmd/mihome-reset/...

sensordb: generate
	$(GOINSTALL) -tags "rpi spi" ./cmd/sensordb-service/...
	$(GOINSTALL) -tags "rpi spi" ./cmd/sensordb-client/...

dummy: generate
	$(GOINSTALL) -tags "rpi spi" ./cmd/mihome-service/...
	$(GOINSTALL) -tags "rpi spi" ./cmd/mihome-client/...

test_protocol: 
	$(GOTEST) -tags rpi ./protocol/...

clean: 
	$(GOCLEAN)
